### ISSUE TITLE
Apply env `JEKYLL_ENV=production`

### ISSUE THREAD

**Issue by robbi5** [ffalt/hookay#1]
hookay should call jekyll with the env variable `JEKYLL_ENV=production` set. 
GitHub Pages is using that when building sites: https://github.com/jekyll/jekyll/issues/1219

We're using it for enabling/disabling piwik: https://github.com/okfde/offenerhaushalt.de/blob/0c3adc02bd3d94680a6b958966a51a17b2a39df0/_includes/tracking.html#L1

**Comment by ffalt** [comment]
thanks for reporting, I added a config setting "env", so you can apply all variables as needed by the site.
```
{
      "name": "some site",
      "branch": "master",
      "build_path": "./data/somesite/build",
      "publish_path": "./data/somesite/site",
      "repro": "https://github.com/somesiteowner/somesite.git",
      "env": {
        "JEKYLL_ENV": "production"
      }
}
```
